registryCredentials:
  enabled: true
  registry: harbor.starburstdata.net/starburstdata
  username: __USERNAME_HARBOR_CHART_REPO__
  password: __PASSWORD_HARBOR_CHART_REPO__

starburstPlatformLicense: starburstdata

expose:
  type: "loadBalancer"
  loadBalancer:
    name: "starburst"
    ports:
      http:
        port: 8080

coordinator:
  etcFiles:
    properties:
      access-control.properties: |
        access-control.name = ranger
        ranger.authentication-type = BASIC
        ranger.username = admin
        ranger.password = RangerPassword1
        ranger.service-name = starburst-enterprise
        ranger.policy-rest-url = http://ranger:6080
        ranger.policy-refresh-interval = 10s
      config.properties: |
        coordinator = true
        node-scheduler.include-coordinator = false
        http-server.http.port = 8080
        discovery-server.enabled = true
        discovery.uri = http://localhost:8080
        insights.persistence-enabled = true
        insights.metrics-persistence-enabled = true
        insights.jdbc.url = jdbc:postgresql://postgresql.default.svc.cluster.local:5432/event_logger
        insights.jdbc.user = postgres
        insights.jdbc.password = __POSTGRES_PASSWORD__
        insights.metrics-collection-interval=15s
        insights.metrics-persistence-interval=60s
        insights.authorized-users = .*
      event-listener.properties: |
        event-listener.name = event-logger
        jdbc.url = jdbc:postgresql://postgresql.default.svc.cluster.local:5432/event_logger
        jdbc.user = postgres
        jdbc.password = __POSTGRES_PASSWORD__
  resources:
    requests:
      memory: "4Gi"
      cpu: 1
    limits:
      memory: "4Gi"
      cpu: 1

worker:
  count: 2
  resources:
    requests:
      memory: "4Gi"
      cpu: 1
    limits:
      memory: "4Gi"
      cpu: 1


catalogs:

  hive: |
    connector.name=hive-hadoop2
    hive.metastore.uri=thrift://hive:9083

  event_logger: |
    connector.name=postgresql
    connection-url=jdbc:postgresql://postgresql.default.svc.cluster.local:5432/event_logger
    connection-user=postgres
    connection-password=__POSTGRES_PASSWORD__
    allow-drop-table=true

  postgresql: |
    connector.name=postgresql
    connection-url=jdbc:postgresql://postgresql.default.svc.cluster.local:5432/postgres
    connection-user=postgres
    connection-password=__POSTGRES_PASSWORD__
    allow-drop-table=true
  tpch: |-
    connector.name=tpch
    tpch.splits-per-node=4